---
  - name: Install master1
    docker_container:
      name: 'master1'
      recreate: true
      restart_policy: unless-stopped
      image: "{{container_name}}:{{container_tag}}"
      capabilities:
        - NET_ADMIN
      volumes:
        - "./index-master1.html:/usr/share/nginx/html/index.html"
        - "./favicon.ico:/usr/share/nginx/html/favicon.ico"
        - "./keepalived-master1.conf:/etc/keepalived/keepalived.conf"
      networks:
        - name: "network_app"
          ipv4_address: "{{ipv4_for_master1}}" 
      purge_networks: no
      networks_cli_compatible: yes
      

  - name: Install slave1
    docker_container:
      name: 'slave1'
      recreate: true
      restart_policy: unless-stopped
      image: "{{container_name}}:{{container_tag}}"
      capabilities:
        - NET_ADMIN
      volumes:
        - "./index-slave1.html:/usr/share/nginx/html/index.html"
        - "./favicon.ico:/usr/share/nginx/html/favicon.ico"
        - "./keepalived-slave1.conf:/etc/keepalived/keepalived.conf"
      networks:
        - name: "network_app"
          ipv4_address: "{{ipv4_for_slave1}}"
      purge_networks: no
      networks_cli_compatible: yes